### ISSUE TITLE
Verwijzing naar leeruitkomsten

### ISSUE THREAD

**Issue by GDWiersma** [tjerk-git/minorwijzer#2]
Hoe komt de student erachter dat de leeruitkomst leidend is voor het assessment?

**Comment by tjerk-git** [comment]
- Leeruitkomsten met niveau's toegevoegd

- Verwijzing vanuit rekening naar leeruitkomsten toegevoegd.

- Toegevoegd aan index als H1 verwijzing  

- Disclaimer toegevoegd bij assessment over leeruitkomsten als beoordelingscriteria.
